#!/usr/bin/env bash

[[ -z "$1" ]] && exit 1

# Batch play for multiple selection
if [[ "$#" -gt 1 ]]; then
    mpc clear
    mpc add "$@"
    mpc play
    exit 0
fi

# Single play logic
SONG="$1"
DIR=$(dirname "$SONG")

mpc clear
mpc add "$DIR"
mpc searchplay filename "$SONG"
mpc single off
mpc repeat off
